/***********************************************************************
 * SNF-Bench axis-specific human study -- Google Apps Script backend.
 *
 * Adapted from the RA-I2V study backend, deliberately reduced. That study
 * asked which clip was better; this one never does. Raters answer only two
 * forced-choice questions, one per failure axis, because the whole point of
 * the benchmark is that "better" conflates the two:
 *
 *   drift  -- which video's background moves more?
 *   decay  -- in which video does the intended motion die out more?
 *
 * Deploy with index.html in the same Apps Script project, paste the generated
 * TRIALS.gs block below, and set SPREADSHEET_ID.
 *
 * Generated pairs come from scripts/make_human_study.py, which samples across
 * small, medium and large metric gaps so agreement is measured over the whole
 * operating range rather than only on obvious cases.
 ***********************************************************************/

const CONFIG = {
  STUDY_TITLE: "Fixed-Camera Video: Background Stability and Motion Persistence",
  APP_VERSION: "snf-bench-axis-study-v1",
  SHEET_NAME: "responses",
  SPREADSHEET_ID: "1E8Y4zZ6mTBqC6keqpYOL-6VJGatljIWuSv77u06KHlw",
  TRIALS_PER_RATER: 24,        // 12 per axis; about 8 minutes
  ALLOW_TIE: true              // indistinguishable pairs must be answerable
};

const QUESTIONS = {
  drift: "Which video's BACKGROUND moves more? Look at things that should stay " +
         "perfectly still: buildings, banks, rocks, the ground, the horizon. " +
         "Ignore the water, fire, rain or smoke.",
  decay: "In which video does the MOVING CONTENT slow down or stop more by the " +
         "end? Look only at what should be moving: water, fire, rain, smoke. " +
         "Ignore whether the background is stable."
};

const INSTRUCTIONS =
  "You will see two short clips side by side, taken from the same scene " +
  "description. Each question asks about ONE specific thing. Please answer only " +
  "that question -- do not judge which video is better overall, and do not " +
  "consider sharpness, colour or realism. If the two clips genuinely look the " +
  "same for the question asked, choose \"about the same\". Answering honestly " +
  "that a pair is indistinguishable is more useful to us than guessing.";

/* ---- paste the contents of TRIALS.gs here -------------------------------- */
// AUTO-GENERATED by scripts/make_human_study.py -- do not hand-edit.
// Fill each videoA/videoB with a shareable URL for the final-window
// excerpt of that system's generation for that prompt.
const TRIALS = [
  {axis: 'drift', idx: 0, prompt: 'An_alpine_meadow_below_snowline_featuring_a_multi-tiered_wat',
   a: 'CausVid', b: 'reward_forcing',
   videoA: 'https://drive.google.com/file/d/1ojYgHXFh9aAdtMvKZbayYmOEPsIAnLcZ/view?usp=drive_link', videoB: 'https://drive.google.com/file/d/1p2oMr-gpoQW8toKrJAOd7_9xDew3FxXq/view?usp=drive_link'},
  {axis: 'drift', idx: 1, prompt: 'A_dangerous_South_Korean_hilly_forest_storm_scene,_recorded_',
   a: 'longlive', b: 'rolling_forcing',
   videoA: 'REPLACEhttps://drive.google.com/file/d/1nhbrktKRMdb61BCvAWx7qoiQN9FAEYyn/view?usp=drive_link_WITH_URL', videoB: 'https://drive.google.com/file/d/10WEJwVDc0mFo1n-ZIXjGOIF1SDci6_YK/view?usp=drive_link'},
  {axis: 'drift', idx: 2, prompt: 'A_high_desert_canyon_scene_featuring_a_wide_river_sweeping_f',
   a: 'infinite_forcing', b: 'reward_forcing',
   videoA: 'https://drive.google.com/file/d/1MJSypogvtc1zlzCWN-zIVBDcMyfv6qp1/view?usp=drive_link', videoB: 'https://drive.google.com/file/d/1ZQzwEMJBtkuk2yYbOkCFHzgniL51kpKV/view?usp=drive_link'},
  {axis: 'drift', idx: 3, prompt: 'A_continuous_South_Korean_rainy_city_street_scene,_recorded_',
   a: 'longlive', b: 'reward_forcing',
   videoA: 'https://drive.google.com/file/d/1RxKBD0hMbtx3hT07O607mP7ctbkLyt6z/view?usp=drive_link', videoB: 'https://drive.google.com/file/d/17kBu2LOjdBahCZFaAjjy5gqG8tWoVtrg/view?usp=drive_link'},
  {axis: 'drift', idx: 4, prompt: 'A_dangerous_South_Korean_hilly_forest_storm_scene,_recorded_',
   a: 'infinite_forcing', b: 'reward_forcing',
   videoA: 'https://drive.google.com/file/d/1ozefvGiiaoCcelsuBv5gvXB11liJKStm/view?usp=drive_link', videoB: 'https://drive.google.com/file/d/1EDqhe6DKOuUCvp92LWjtXVpVyuxN5PQR/view?usp=drive_link'},
  {axis: 'drift', idx: 5, prompt: 'A_continuous_South_Korean_urban_town_street_scene_during_sno',
   a: 'CausVid', b: 'self_forcing',
   videoA: 'https://drive.google.com/file/d/1gV6vn8_NHNu9XAONCZrE8dlna63dZGWW/view?usp=drive_link', videoB: 'https://drive.google.com/file/d/1l4H_V-PuItNJvudlzRPk2hv3Dv5bzywX/view?usp=drive_link'},
  {axis: 'drift', idx: 6, prompt: 'A_serene_woodland_stream_scene,_recorded_by_a_completely_fix',
   a: 'causal_forcing', b: 'reward_forcing',
   videoA: 'https://drive.google.com/file/d/1GrCYPFaW4fV75SU1NZcso5tbUEdyCLDJ/view?usp=drive_link', videoB: 'https://drive.google.com/file/d/1J28cQORFfAueFlwum9qb6wmT7BqCo88t/view?usp=drive_link'},
  {axis: 'drift', idx: 7, prompt: 'A_South_Korean_countryside_scene_featuring_a_wide_river_stre',
   a: 'longlive', b: 'self_forcing',
   videoA: 'https://drive.google.com/file/d/11Fo3M4t4hVrZwcIM4HHPfX-gcdYZtj1e/view?usp=drive_link', videoB: 'https://drive.google.com/file/d/1C57kBA1h2JFXl31s78CsX1w0CPx7WhvE/view?usp=drive_link'},
  {axis: 'drift', idx: 8, prompt: 'A_stunning_tranquil_river_scene_beneath_a_concrete_bridge,_r',
   a: 'causal_forcing', b: 'reward_forcing',
   videoA: 'https://drive.google.com/file/d/1n9vsbE2CZbWl0Wk9KPTWwCnaUm3DW5dZ/view?usp=drive_link', videoB: 'https://drive.google.com/file/d/1WB6B6FB0Iw7Y49klHbj_ygXgyxGfxxN6/view?usp=drive_link'},
  {axis: 'drift', idx: 9, prompt: 'A_stunning_tranquil_river_scene_beneath_a_concrete_bridge,_r',
   a: 'CausVid', b: 'infinite_forcing',
   videoA: 'https://drive.google.com/file/d/188DpUJn7F0ttir8VUjKaZLEVBeF0Nft_/view?usp=drive_link', videoB: 'https://drive.google.com/file/d/1uCUxJ-JgJ8nKpAS_APa26Eh5kilSioZD/view?usp=drive_link'},
  {axis: 'drift', idx: 10, prompt: 'A_storm-swollen_rural_stream,_recorded_by_a_fixed_tripod_cam',
   a: 'longlive', b: 'reward_forcing',
   videoA: 'https://drive.google.com/file/d/14eFqyTOyDzRAJ-x6FIgNCkH9gp8H13L_/view?usp=drive_link', videoB: 'https://drive.google.com/file/d/1j74PBWRXQ1HIs2hbT8GA5DKRs3mUieHa/view?usp=drive_link'},
  {axis: 'drift', idx: 11, prompt: 'A_dangerous_rural_South_Korean_river_scene_at_night,_recorde',
   a: 'CausVid', b: 'self_forcing',
   videoA: 'https://drive.google.com/file/d/1Z3KE7bniG2UVUS0toDVGXwddZHX2rpFT/view?usp=drive_link', videoB: 'https://drive.google.com/file/d/129Rza6vL_L_o0ehsPG3pK9VscpcTfUsd/view?usp=drive_link'},
  {axis: 'decay', idx: 0, prompt: 'A_continuous_South_Korean_rainy_city_street_scene,_recorded_',
   a: 'reward_forcing', b: 'self_forcing',
   videoA: 'https://drive.google.com/file/d/17kBu2LOjdBahCZFaAjjy5gqG8tWoVtrg/view?usp=drive_link', videoB: 'https://drive.google.com/file/d/1YZR7_CdJPkxbdeoiDSykca-_mcGCXxV1/view?usp=drive_link'},
  {axis: 'decay', idx: 1, prompt: 'A_tranquil_mountain_stream_in_a_rural_South_Korean_valley,_r',
   a: 'infinite_forcing', b: 'longlive',
   videoA: 'https://drive.google.com/file/d/1tyBIrYCX7AGeWjcwS-DJXbBwaDG5jrL4/view?usp=drive_link', videoB: 'https://drive.google.com/file/d/1R_XsdTx_lnOQuPSbHtvRNOeweMZ9T57q/view?usp=drive_link'},
  {axis: 'decay', idx: 2, prompt: 'A_dangerous_South_Korean_hilly_forest_storm_scene,_recorded_',
   a: 'causal_forcing', b: 'infinite_forcing',
   videoA: 'https://drive.google.com/file/d/105F_4kBb4tnL4Xsizl1wcqgy2BIuJG5B/view?usp=drive_link', videoB: 'https://drive.google.com/file/d/1ozefvGiiaoCcelsuBv5gvXB11liJKStm/view?usp=drive_link'},
  {axis: 'decay', idx: 3, prompt: 'An_alpine_meadow_below_snowline_featuring_a_multi-tiered_wat',
   a: 'CausVid', b: 'reward_forcing',
   videoA: 'https://drive.google.com/file/d/1ojYgHXFh9aAdtMvKZbayYmOEPsIAnLcZ/view?usp=drive_link', videoB: 'https://drive.google.com/file/d/1p2oMr-gpoQW8toKrJAOd7_9xDew3FxXq/view?usp=drive_link'},
  {axis: 'decay', idx: 4, prompt: 'A_high_desert_canyon_scene_featuring_a_wide_river_sweeping_f',
   a: 'causal_forcing', b: 'self_forcing',
   videoA: 'https://drive.google.com/file/d/1mfZ4LSIyzoF-r8lnlgYxxkG34NxtsfcR/view?usp=drive_link', videoB: 'https://drive.google.com/file/d/1Q516F0d4lNTCgqWoHNJTvj9_0tKj8Rx_/view?usp=drive_link'},
  {axis: 'decay', idx: 5, prompt: 'An_urban_storm_drain_canal,_recorded_by_a_static_tripod_came',
   a: 'longlive', b: 'self_forcing',
   videoA: 'https://drive.google.com/file/d/1tGkJIdzBHJtThzGI6AzmeYN2zTGA_HLi/view?usp=sharing', videoB: 'https://drive.google.com/file/d/1YYdlrYVkyedE-QpTIJQc5EHRLOgw2ewA/view?usp=drive_link'},
  {axis: 'decay', idx: 6, prompt: 'A_stormy_sea_cliff_in_South_Korea,_recorded_by_a_static_trip',
   a: 'causal_forcing', b: 'infinite_forcing',
   videoA: 'https://drive.google.com/file/d/1sUMA8jeEr7W8sriVuHfr7fY9Saht9PDc/view?usp=drive_link', videoB: 'https://drive.google.com/file/d/1qJmnGmb90SjTJzGLcDCuIJ_JKGb_LhKq/view?usp=drive_link'},
  {axis: 'decay', idx: 7, prompt: 'A_beautiful_South_Korean_empty_sea_beach_scene,_recorded_by_',
   a: 'reward_forcing', b: 'self_forcing',
   videoA: 'https://drive.google.com/file/d/1ZCkEB2ahxEMNkoFFGqHYgjSR8ZE0s5Yk/view?usp=drive_link', videoB: 'https://drive.google.com/file/d/19WmB2hLNGPSOcR-8YHj41mrTFn9eZLSJ/view?usp=drive_link'},
  {axis: 'decay', idx: 8, prompt: 'A_storm-swollen_rural_stream,_recorded_by_a_fixed_tripod_cam',
   a: 'CausVid', b: 'longlive',
   videoA: 'https://drive.google.com/file/d/1EFoJUMksD1JjZdCo4rrKwD9VdFByamFm/view?usp=drive_link', videoB: 'https://drive.google.com/file/d/14eFqyTOyDzRAJ-x6FIgNCkH9gp8H13L_/view?usp=drive_link'},
  {axis: 'decay', idx: 9, prompt: 'A_Pacific_Northwest_old-growth_forest_scene_featuring_a_casc',
   a: 'causal_forcing', b: 'longlive',
   videoA: 'https://drive.google.com/file/d/1lqniVFRMJWStFcR3jJXJKGuRffVu5K87/view?usp=drive_link', videoB: 'https://drive.google.com/file/d/1fv3NhkY5qeLIEQWCvmWxRXDfIwTko1tv/view?usp=drive_link'},
  {axis: 'decay', idx: 10, prompt: 'A_tropical_jungle_clearing_featuring_a_broad_lowland_river_c',
   a: 'CausVid', b: 'rolling_forcing',
   videoA: 'https://drive.google.com/file/d/18LF26zdXHfFBVq_SdwJGOi5xJy_E2E5Z/view?usp=drive_link', videoB: 'https://drive.google.com/file/d/1axQ53tVG9thPjGkuY6JMQ2NueAVz3YAv/view?usp=drive_link'},
  {axis: 'decay', idx: 11, prompt: 'An_ancient_stone_city_waterway_featuring_fast-moving_rapids_',
   a: 'causal_forcing', b: 'reward_forcing',
   videoA: 'https://drive.google.com/file/d/1EE8-AejTSauUfHkDR2FsQcSzjuN1k8MD/view?usp=drive_link', videoB: 'https://drive.google.com/file/d/1k01prvd1i2evS4rbcGWbF2xuQIm6ion-/view?usp=drive_link'},
];
/* ------------------------------------------------------------------------- */

function doGet() {
  return HtmlService.createTemplateFromFile('index')
      .evaluate()
      .setTitle(CONFIG.STUDY_TITLE)
      .addMetaTag('viewport', 'width=device-width, initial-scale=1');
}

function getConfig() {
  return {
    title: CONFIG.STUDY_TITLE,
    instructions: INSTRUCTIONS,
    questions: QUESTIONS,
    allowTie: CONFIG.ALLOW_TIE,
    nTrials: Math.min(CONFIG.TRIALS_PER_RATER, TRIALS.length)
  };
}

/**
 * Trials are served in a per-rater random order, and A/B presentation side is
 * randomised per trial. Without both, a rater who notices that one column is
 * usually the drifting one stops judging the video and starts judging the
 * layout.
 */
function getTrials(raterId) {
  const seed = hashString(raterId || 'anon');
  const order = shuffleWithSeed(TRIALS.map((_, i) => i), seed)
      .slice(0, CONFIG.TRIALS_PER_RATER);
  return order.map(function (i, k) {
    const t = TRIALS[i];
    const flip = ((seed + i) % 2) === 1;
    return {
      trialIndex: k,
      trialId: i,
      axis: t.axis,
      question: QUESTIONS[t.axis],
      prompt: t.prompt.replace(/_/g, ' '),
      left: toPlayableUrl_(flip ? t.videoB : t.videoA),
      right: toPlayableUrl_(flip ? t.videoA : t.videoB),
      flipped: flip
    };
  });
}

/**
 * Records one response. `choice` is 'left' | 'right' | 'same'; it is resolved
 * back to a system key here, so the client never learns which system is which.
 */
function submitResponse(payload) {
  const ss = SpreadsheetApp.openById(CONFIG.SPREADSHEET_ID);
  let sheet = ss.getSheetByName(CONFIG.SHEET_NAME);
  if (!sheet) {
    sheet = ss.insertSheet(CONFIG.SHEET_NAME);
    sheet.appendRow(['timestamp', 'version', 'raterId', 'trialId', 'axis',
                     'prompt', 'systemA', 'systemB', 'flipped', 'choice',
                     'chosenSystem', 'dwellMs', 'playbackProblem']);
  }
  if (!payload || !Number.isInteger(Number(payload.trialId)) || !TRIALS[payload.trialId]) {
    throw new Error('Invalid trial response.');
  }
  if (['left', 'right', 'same'].indexOf(payload.choice) === -1) {
    throw new Error('Invalid response choice.');
  }
  const t = TRIALS[Number(payload.trialId)];
  const expectedFlip = ((hashString(String(payload.raterId || 'anon')) +
                         Number(payload.trialId)) % 2) === 1;
  let chosen = '';
  if (payload.choice === 'same') {
    chosen = 'same';
  } else {
    const pickedLeft = payload.choice === 'left';
    chosen = (pickedLeft !== expectedFlip) ? t.a : t.b;
  }
  sheet.appendRow([new Date(), CONFIG.APP_VERSION, payload.raterId,
                   payload.trialId, t.axis, t.prompt, t.a, t.b,
                   expectedFlip, payload.choice, chosen,
                   payload.dwellMs || '', Boolean(payload.playbackProblem)]);
  return { ok: true };
}

/* ---- helpers ------------------------------------------------------------ */
function toPlayableUrl_(url) {
  // Keep every pasted URL verbatim in TRIALS. Only derive an embeddable URL
  // when serving it to the browser. This also tolerates accidental text
  // surrounding an otherwise valid Drive share URL.
  const match = String(url || '').match(/drive\.google\.com\/file\/d\/([\w-]+)/);
  return match ? 'https://drive.google.com/file/d/' + match[1] + '/preview' : url;
}

function hashString(s) {
  let h = 0;
  for (let i = 0; i < s.length; i++) { h = (h * 31 + s.charCodeAt(i)) | 0; }
  return Math.abs(h);
}

function shuffleWithSeed(arr, seed) {
  const a = arr.slice();
  let s = seed || 1;
  for (let i = a.length - 1; i > 0; i--) {
    s = (s * 1103515245 + 12345) & 0x7fffffff;
    const j = s % (i + 1);
    const tmp = a[i]; a[i] = a[j]; a[j] = tmp;
  }
  return a;
}
