#!/usr/bin/env python3
"""Content hashes for every input file of each prompt set; fail on any drift.

A version is only something you can go back to if you can tell when it has
changed. Git history answers that for committed files, but not for a file
edited in a worktree, copied into another repository, or regenerated by a
builder whose output happens to differ -- and the v2 I2V images are now
consumed from two repositories at once. This records a sha256 for every file
that defines what a model is given, per prompt set, in
`manifest/prompt_set_hashes.json`, and `--check` (the default) fails if any
file is missing, extra, or different.

Scope is inputs only: prompts, captions, crop metadata, conditioning images,
and the manifests they are exported from. Code and results are versioned by
git and by the record-level `prompt_set` / `metric_spec_version` labels.

    python scripts/freeze_prompt_sets.py            # verify
    python scripts/freeze_prompt_sets.py --write    # re-freeze (deliberate)

Re-freezing v1 should never be necessary: v1 is the submitted set and is
byte-identical from the last pre-v2 commit (729219b) to now.
"""

import argparse
import glob
import hashlib
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "manifest", "prompt_set_hashes.json")

PATTERNS = {
    "v1": ["prompts/t2v/*.txt",
           "prompts/i2v/*/*.json",
           "prompts/i2v/*/*/*"],
    "v2": ["manifest/prompts_v2.json",
           "manifest/i2v_pairs_v2.json",
           "manifest/i2v_pair_sources.json",
           "prompts/v2/core.txt",
           "prompts/v2/t2v/*.txt",
           "prompts/v2/i2v/core.txt",
           "prompts/v2/i2v/images/*.jpg",
           "prompts/v2/i2v/snf_v2_*/target_crop_info_v2.json"],
}


def sha(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _through_link(path):
    """True if any directory between ROOT and `path` is a symlink.

    Both sets expose loader-layout aliases (`16-9 -> images` for v1, `v2/<id>.jpg
    -> ../../images/<id>.jpg` for v2); hashing through them would count every
    image twice and report the alias as drift.
    """
    rel = os.path.relpath(path, ROOT).split(os.sep)
    cur = ROOT
    for part in rel[:-1]:
        cur = os.path.join(cur, part)
        if os.path.islink(cur):
            return True
    return False


def current(name):
    files = set()
    for pat in PATTERNS[name]:
        files.update(p for p in glob.glob(os.path.join(ROOT, pat))
                     if os.path.isfile(p) and not os.path.islink(p)
                     and not _through_link(p))
    return {os.path.relpath(p, ROOT): sha(p) for p in sorted(files)}


def fingerprint(files):
    """One short string identifying a set's exact inputs, for run records.

    A render records *which* prompt set it consumed by path; this lets it record
    *what* that set contained, so a run made before an edit can be told apart
    from one made after. `python scripts/freeze_prompt_sets.py --fingerprint v2`
    prints it.
    """
    blob = json.dumps(files, sort_keys=True).encode()
    return "sha256:" + hashlib.sha256(blob).hexdigest()[:16]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--fingerprint", choices=sorted(PATTERNS))
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--set", choices=sorted(PATTERNS), action="append")
    a = ap.parse_args()
    names = a.set or sorted(PATTERNS)

    frozen = json.load(open(OUT)) if os.path.exists(OUT) else {}
    if a.fingerprint:
        print(frozen[a.fingerprint]["fingerprint"])
        return 0
    if a.write:
        for n in names:
            frozen[n] = {"n_files": 0, "files": current(n)}
            frozen[n]["n_files"] = len(frozen[n]["files"])
            frozen[n]["fingerprint"] = fingerprint(frozen[n]["files"])
            print(f"froze {n}: {frozen[n]['n_files']} files")
        with open(OUT, "w") as fh:
            json.dump(frozen, fh, indent=1, sort_keys=True)
            fh.write("\n")
        return 0

    bad = 0
    for n in names:
        if n not in frozen:
            print(f"{n}: never frozen; run with --write")
            bad += 1
            continue
        want, have = frozen[n]["files"], current(n)
        missing = sorted(set(want) - set(have))
        extra = sorted(set(have) - set(want))
        changed = sorted(f for f in set(want) & set(have) if want[f] != have[f])
        if missing or extra or changed:
            bad += 1
            print(f"{n}: DRIFT -- {len(changed)} changed, {len(missing)} missing, "
                  f"{len(extra)} new")
            for label, fs in (("changed", changed), ("missing", missing),
                              ("new", extra)):
                for f in fs[:5]:
                    print(f"   {label}: {f}")
        else:
            print(f"{n}: {len(want)} files match the freeze "
                  f"({frozen[n].get('fingerprint', 'no fingerprint')})")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
